name: Deploy Blockchain DevTest Lab

on:
  push:
    paths:
      - 'devtest-lab/blockchain-devtestlab-environment.bicep'
      - 'devtest-lab/parameters/blockchain-env.parameters.json'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Validate Bicep
        run: az deployment group validate \
              --resource-group ${{ secrets.DEVTEST_LAB_RG }} \
              --template-file devtest-lab/blockchain-devtestlab-environment.bicep \
              --parameters @devtest-lab/parameters/blockchain-env.parameters.json

      - name: Deploy Blockchain Env
        run: az deployment group create \
              --resource-group ${{ secrets.DEVTEST_LAB_RG }} \
              --template-file devtest-lab/blockchain-devtestlab-environment.bicep \
              --parameters @devtest-lab/parameters/blockchain-env.parameters.json
