
name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: npm install
          
      - name: Run tests
        run: npm test
        
      - name: Debug file structure
        run: |
          echo "Listing scripts directory:"
          find . -name "scripts" -type d | xargs ls -la
          
          echo "Finding deploy.js file:"
          find . -name "deploy.js"

        # Change this command to point to the correct path
      - name: Deploy smart contracts
        run: |
         cd smart-contracts
         node scripts/deploy.js
        
      - name: Deploy smart contracts
        run: npm run deploy:contracts