# ------------------------------------------------------------
# .github/workflows/devtest-lab-ci.yml
# ------------------------------------------------------------
name: Deploy DevTest Lab

on:
  workflow_run:
    workflows: ["Deploy Landing Zone"]
    types:
      - completed

permissions:
  id-token: write
  contents: read

jobs:
  deploy-devtest-lab:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login using OIDC
        uses: azure/login@v1
        with:
          client-id:       ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id:       ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy DevTest Lab VM via Bicep
        run: |
          az deployment group create \
            --resource-group DevTest-RG \
            --template-file devtest-lab/devtest-vm.bicep \
            --parameters devtest-lab/parameters/devtest-vm.parameters.json

      - name: Configure NSG Hardening on Deployed VM
        run: |
          VM_NAME=$(jq -r '.vmName.value' devtest-lab/parameters/devtest-vm.parameters.json)
          az vm run-command invoke \
            --resource-group DevTest-RG \
            --name "$VM_NAME" \
            --command-id RunPowerShellScript \
            --scripts "@devtest-lab/scripts/configure-nsg.ps1"

      - name: Enable Diagnostics Extension
        run: |
          VM_NAME=$(jq -r '.vmName.value' devtest-lab/parameters/devtest-vm.parameters.json)
          az vm run-command invoke \
            --resource-group DevTest-RG \
            --name "$VM_NAME" \
            --command-id RunPowerShellScript \
            --scripts "@devtest-lab/scripts/enable-diagnostics.ps1"

      - name: Enable Just-In-Time Access
        run: |
          VM_NAME=$(jq -r '.vmName.value' devtest-lab/parameters/devtest-vm.parameters.json)
          az vm run-command invoke \
            --resource-group DevTest-RG \
            --name "$VM_NAME" \
            --command-id RunPowerShellScript \
            --scripts "@devtest-lab/scripts/enable-jit.ps1"
