# ==========================================================================
# Enterprise Azure Landing Zone - Management Resources Deployment
# ==========================================================================
# PROMPT ENGINEERING GUIDANCE:
# This workflow deploys core management resources for an enterprise landing zone:
# - Log Analytics workspace and solutions
# - Azure Automation account
# - Azure Monitor and Alerts
# - Update Management solution
# - Centralized diagnostic settings
#
# SECRETS CONFIGURATION:
# - AZURE_TENANT_ID: Your Azure Active Directory tenant ID
# - AZURE_CLIENT_ID: App registration client ID with federated credentials
# - MANAGEMENT_SUBSCRIPTION_ID: Dedicated subscription for management resources
#
# CUSTOMIZATION TIPS:
# - Adjust retention periods based on your compliance requirements
# - Configure alert thresholds appropriate for your workloads
# - Consider data residency requirements when selecting region

name: Deploy Management Resources

on:
  push:
    branches:
      - main
    paths:
      - 'management/**'
      - '.github/workflows/deploy-management.yml'
  
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - nonproduction
          - development
      region:
        description: 'Azure region for deployment'
        required: true
        default: 'eastus2'
        type: string

permissions:
  id-token: write  # Required for OIDC federation
  contents: read   # Required to read repo files

# ==========================================================================
# ENVIRONMENT VARIABLES - CRITICAL SECRET CONFIGURATION
# ==========================================================================
# PROMPT GUIDANCE:
# - Management subscription should be separate from other workloads
# - MANAGEMENT_SUBSCRIPTION_ID must exist as a repository secret
# - The service principal needs Log Analytics Contributor and Monitoring Contributor
# - Consider data residency requirements when selecting workspace region
# ==========================================================================
env:
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  MANAGEMENT_SUBSCRIPTION_ID: ${{ secrets.MANAGEMENT_SUBSCRIPTION_ID }}
  RESOURCE_GROUP_NAME: rg-management
  LOCATION: ${{ github.event.inputs.region || 'eastus2' }}
  ENVIRONMENT: ${{ github.event.inputs.environment || 'production' }}

jobs:
  verify-prerequisites:
    name: Verify Prerequisites
    runs-on: ubuntu-latest
    steps:
      - name: Check required secrets
        run: |
          # Verify tenant ID
          if [ -z "${{ secrets.AZURE_TENANT_ID }}" ]; then
            echo "::error::AZURE_TENANT_ID secret is not set"
            exit 1
          fi
          
          # Verify client ID
          if [ -z "${{ secrets.AZURE_CLIENT_ID }}" ]; then
            echo "::error::AZURE_CLIENT_ID secret is not set"
            exit 1
          fi
          
          # Verify subscription ID
          if [ -z "${{ secrets.MANAGEMENT_SUBSCRIPTION_ID }}" ]; then
            echo "::error::MANAGEMENT_SUBSCRIPTION_ID secret is not set"
            exit 1
          fi
          
          echo "All required secrets are configured."
          
          # Determine subscription to use
          SUB_ID="${{ secrets.MANAGEMENT_SUBSCRIPTION_ID }}"
          echo "Using subscription ID: ${SUB_ID:0:8}..."
          echo "SUBSCRIPTION_ID=$SUB_ID" >> $GITHUB_ENV

  # Additional management-specific deployment jobs would follow...