# ==================================================================================
# Enterprise Azure Landing Zone - Identity Resources Deployment 
# ==================================================================================

name: Deploy Identity Resources

on:
  push:
    branches:
      - main
    paths:
      - 'modules/*.bicep'
      - 'landing-zone/identity-main.bicep'
      - 'landing-zone/parameters/identity.parameters.json'
      - '.github/workflows/deploy-identity.yml'
  
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - nonproduction
          - development
      region:
        description: 'Azure region for deployment'
        required: true
        default: 'eastus2'
        type: string

# [... rest of the workflow file ...]

# Example deployment step:
- name: Deploy identity resources
  run: |
    echo "Deploying identity infrastructure..."
    
    # Notice we're referencing the Bicep files at their proper locations
    az deployment group create \
      --name "identity-$(date +%Y%m%d%H%M%S)" \
      --resource-group ${{ env.RESOURCE_GROUP_NAME }} \
      --template-file landing-zone/identity-main.bicep \
      --parameters @landing-zone/parameters/identity.parameters.json \
                 environment=${{ env.ENVIRONMENT }} \
                 location=${{ env.LOCATION }} \
                 tenantId=${{ env.AZURE_TENANT_ID }}
    
    echo "Identity deployment completed."