name: Deploy Management Resources

# Prompt: Trigger the workflow manually, or on push to main branch
on:
  workflow_dispatch:
  push:
    branches:
      - main

# Add this permissions block - this is what's missing for OIDC authentication
permissions:
  id-token: write
  contents: read

jobs:
  deploy-management:
    runs-on: ubuntu-latest

    # Prompt: Set environment variables for re-use and clarity
    env:
      RESOURCE_GROUP_NAME: rg-management
      LOCATION: eastus2
      ENVIRONMENT: production

    steps:
      # Prompt: Always begin with a checkout of the code to access Bicep templates
      - name: Checkout repository
        uses: actions/checkout@v3

      # Prompt: Authenticate with Azure using secure GitHub secrets
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MANAGEMENT_SUBSCRIPTION_ID }}

      # Rest of your existing steps remain unchanged