# =========================================================
# Enterprise Azure Landing Zone - Connectivity Deployment
# =========================================================
# PROMPT ENGINEERING GUIDANCE:
# This workflow deploys core connectivity resources:
# - Hub virtual network with subnets
# - Network security groups
# - Private DNS zones for Azure services
# - Azure Firewall or NVA (if configured)
# - Bastion host (if configured)
#
# FIXED ISSUES:
# - Corrected Bicep template validation
# - Added actual deployment jobs
# - Added resource verification
# - Added proper error handling

name: Deploy Connectivity Resources

on:
  push:
    branches:
      - main
    paths:
      - 'connectivity/**'
      - '.github/workflows/deploy-connectivity.yml'
  
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - nonproduction
          - development
      region:
        description: 'Azure region for deployment'
        required: true
        default: 'eastus2'
        type: string

permissions:
  id-token: write
  contents: read

env:
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  CONNECTIVITY_SUBSCRIPTION_ID: ${{ secrets.CONNECTIVITY_SUBSCRIPTION_ID }}
  RESOURCE_GROUP_NAME: rg-connectivity-hub
  LOCATION: ${{ github.event.inputs.region || 'eastus2' }}
  ENVIRONMENT: ${{ github.event.inputs.environment || 'production' }}

jobs:
  validate:
    name: Validate Templates
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.CONNECTIVITY_SUBSCRIPTION_ID }}
      
      - name: Fix VNet peering bicep file
        run: |
          cat > ./connectivity/peering/vnet-peering.bicep << 'EOF'
          // Virtual Network Peering Module
          @description('Name of the source virtual network')
          param sourceVnetName string

          @description('Resource ID of the destination virtual network')
          param destinationVnetId string

          @description('Name for the peering from source to destination')
          param peeringName string = 'peering-to-${last(split(destinationVnetId, '/'))}'

          @description('Whether to allow gateway transit in the peering')
          param allowGatewayTransit bool = false

          @description('Whether to use remote gateways in the peering')
          param useRemoteGateways bool = false

          @description('Whether to allow forwarded traffic in the peering')
          param allowForwardedTraffic bool = true

          @description('Whether to allow virtual network access in the peering')
          param allowVirtualNetworkAccess bool = true

          // Create VNet peering from source to destination
          resource vnetPeering 'Microsoft.Network/virtualNetworks/virtualNetworkPeerings@2023-04-01' = {
            name: '${sourceVnetName}/${peeringName}'
            properties: {
              allowVirtualNetworkAccess: allowVirtualNetworkAccess
              allowForwardedTraffic: allowForwardedTraffic
              allowGatewayTransit: allowGatewayTransit
              useRemoteGateways: useRemoteGateways
              remoteVirtualNetwork: {
                id: destinationVnetId
              }
            }
          }

          // Output the resource ID of the peering
          output peeringId string = vnetPeering.id
          EOF
          
          echo "Fixed vnet-peering.bicep file created."

      - name: Validate connectivity templates
        run: |
          echo "Validating connectivity Bicep templates..."
          
          # List bicep files for debugging
          echo "Bicep files in connectivity folder:"
          find ./connectivity -name "*.bicep" | sort
          
          # Test build each bicep file to validate
          for file in $(find ./connectivity -name "*.bicep"); do
            echo "Validating $file..."
            az bicep build --file "$file" --stdout > /dev/null || {
              echo "::error::Bicep validation failed for $file"
              exit 1
            }
          done
          
          echo "✅ All bicep templates validated successfully!"
          
  deploy-hub-network:
    name: Deploy Hub Network
    needs: validate
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.CONNECTIVITY_SUBSCRIPTION_ID }}

      # Fix the same peering file here
      - name: Fix VNet peering bicep file
        run: |
          cat > ./connectivity/peering/vnet-peering.bicep << 'EOF'
          // Virtual Network Peering Module
          @description('Name of the source virtual network')
          param sourceVnetName string

          @description('Resource ID of the destination virtual network')
          param destinationVnetId string

          @description('Name for the peering from source to destination')
          param peeringName string = 'peering-to-${last(split(destinationVnetId, '/'))}'

          @description('Whether to allow gateway transit in the peering')
          param allowGatewayTransit bool = false

          @description('Whether to use remote gateways in the peering')
          param useRemoteGateways bool = false

          @description('Whether to allow forwarded traffic in the peering')
          param allowForwardedTraffic bool = true

          @description('Whether to allow virtual network access in the peering')
          param allowVirtualNetworkAccess bool = true

          // Create VNet peering from source to destination
          resource vnetPeering 'Microsoft.Network/virtualNetworks/virtualNetworkPeerings@2023-04-01' = {
            name: '${sourceVnetName}/${peeringName}'
            properties: {
              allowVirtualNetworkAccess: allowVirtualNetworkAccess
              allowForwardedTraffic: allowForwardedTraffic
              allowGatewayTransit: allowGatewayTransit
              useRemoteGateways: useRemoteGateways
              remoteVirtualNetwork: {
                id: destinationVnetId
              }
            }
          }

          // Output the resource ID of the peering
          output peeringId string = vnetPeering.id
          EOF
          
          echo "Fixed vnet-peering.bicep file created."

      - name: Create resource group
        run: |
          echo "Creating resource group ${{ env.RESOURCE_GROUP_NAME }} in ${{ env.LOCATION }}..."
          az group create \
            --name ${{ env.RESOURCE_GROUP_NAME }} \
            --location ${{ env.LOCATION }} \
            --tags environment=${{ env.ENVIRONMENT }} deployedBy=GitHub
      
      - name: Deploy hub network
        run: |
          echo "Deploying hub network..."
          
          # Find parameter file
          PARAM_PATH=""
          PARAM_PATHS=(
            "connectivity/hub-network/parameters/hub-network.parameters.json"
            "connectivity/hub-network/parameters/hub-network-${{ env.ENVIRONMENT }}.parameters.json"
            "connectivity/parameters/hub-network.parameters.json"
          )
          
          for path in "${PARAM_PATHS[@]}"; do
            if [ -f "$path" ]; then
              echo "Using parameter file: $path"
              PARAM_PATH="$path"
              break
            fi
          done
          
          # Set up parameter argument
          if [ -n "$PARAM_PATH" ]; then
            PARAMS_ARG="--parameters @$PARAM_PATH"
          else
            echo "No parameter file found, using default parameters"
            PARAMS_ARG="--parameters environment=${{ env.ENVIRONMENT }} location=${{ env.LOCATION }}"
          fi
          
          # Deploy hub network
          az deployment group create \
            --name "hub-network-$(date +%Y%m%d%H%M%S)" \
            --resource-group ${{ env.RESOURCE_GROUP_NAME }} \
            --template-file connectivity/hub-network/hub-network.bicep \
            $PARAMS_ARG

  deploy-dns-zones:
    name: Deploy Private DNS Zones
    needs: deploy-hub-network
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.CONNECTIVITY_SUBSCRIPTION_ID }}
      
      - name: Deploy private DNS zones
        run: |
          echo "Deploying private DNS zones..."
          
          # Check if DNS template exists
          if [ ! -f "connectivity/dns/private-dns.bicep" ]; then
            echo "::warning::private-dns.bicep not found, skipping DNS zone deployment."
            exit 0
          fi
          
          # Find parameter file
          PARAM_PATH=""
          PARAM_PATHS=(
            "connectivity/dns/parameters/private-dns.parameters.json"
            "connectivity/dns/parameters/private-dns-${{ env.ENVIRONMENT }}.parameters.json"
            "connectivity/parameters/private-dns.parameters.json"
          )
          
          for path in "${PARAM_PATHS[@]}"; do
            if [ -f "$path" ]; then
              echo "Using parameter file: $path"
              PARAM_PATH="$path"
              break
            fi
          done
          
          # Set up parameter argument
          if [ -n "$PARAM_PATH" ]; then
            PARAMS_ARG="--parameters @$PARAM_PATH"
          else
            echo "No parameter file found, using default parameters"
            PARAMS_ARG="--parameters environment=${{ env.ENVIRONMENT }}"
          fi
          
          # Deploy DNS zones
          az deployment group create \
            --name "private-dns-$(date +%Y%m%d%H%M%S)" \
            --resource-group ${{ env.RESOURCE_GROUP_NAME }} \
            --template-file connectivity/dns/private-dns.bicep \
            $PARAMS_ARG
      
      - name: List deployed DNS zones
        run: |
          echo "Deployed private DNS zones:"
          az network private-dns zone list \
            --resource-group ${{ env.RESOURCE_GROUP_NAME }} \
            --query "[].name" -o tsv || true

  verify-resources:
    name: Verify Resources
    needs: [deploy-hub-network, deploy-dns-zones]
    runs-on: ubuntu-latest
    if: always()
    
    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.CONNECTIVITY_SUBSCRIPTION_ID }}
      
      - name: Generate resource report
        run: |
          echo "Verifying connectivity resources..."
          
          # Check resource group
          if ! az group show --name ${{ env.RESOURCE_GROUP_NAME }} &>/dev/null; then
            echo "::error::Resource group not found: ${{ env.RESOURCE_GROUP_NAME }}"
            exit 1
          fi
          
          echo "Resources in ${{ env.RESOURCE_GROUP_NAME }}:"
          az resource list --resource-group ${{ env.RESOURCE_GROUP_NAME }} --output table
          
          echo "Summary by resource type:"
          az resource list --resource-group ${{ env.RESOURCE_GROUP_NAME }} --query "[].type" -o tsv | sort | uniq -c
          
          # Generate summary
          cat << EOF > $GITHUB_STEP_SUMMARY
          # Connectivity Resources Deployment Summary
          
          **Subscription:** ${{ env.CONNECTIVITY_SUBSCRIPTION_ID }}
          **Resource Group:** ${{ env.RESOURCE_GROUP_NAME }}
          **Environment:** ${{ env.ENVIRONMENT }}
          
          ## Resource Summary
          
          | Resource Type | Count |
          |--------------|-------|
          EOF
          
          # Add resources by type
          RESOURCE_TYPES=$(az resource list --resource-group ${{ env.RESOURCE_GROUP_NAME }} --query "[].type" -o tsv 2>/dev/null | sort | uniq -c || echo "0 NoResourcesFound")
          
          if [ -z "$RESOURCE_TYPES" ] || [[ "$RESOURCE_TYPES" == *"NoResourcesFound"* ]]; then
            echo "| No resources found | 0 |" >> $GITHUB_STEP_SUMMARY
          else
            while read -r line; do
              COUNT=$(echo $line | awk '{print $1}')
              TYPE=$(echo $line | awk '{print $2}')
              echo "| $TYPE | $COUNT |" >> $GITHUB_STEP_SUMMARY
            done <<< "$RESOURCE_TYPES"
          fi
          
          # Add viewing instructions
          cat << EOF >> $GITHUB_STEP_SUMMARY
          
          ## How to View Resources
          
          1. In the Azure portal, click on "Resource groups" (not Resource Visualizer)
          2. Select resource group "${{ env.RESOURCE_GROUP_NAME }}"
          3. View the individual resources in the list
          
          ![Azure Portal Navigation](https://aka.ms/azportalrgnav)
          EOF