# File: .github/workflows/hardhat-ci.yml
name: Hardhat CI

on:
  push:
    paths:
      - 'smart-contracts/scripts/**'

jobs:
  compile-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci
        working-directory: smart-contracts

      - name: Run Hardhat tests
        run: npm test
        working-directory: smart-contracts

      - name: Deploy contracts via Azure (optional)
        if: success()
        run: |
          node deploy.js
        working-directory: smart-contracts
