#CI/CD for infrastructure
name: Deploy Landing Zone

on:
  push:
    paths:
      - 'landing-zone/landing-zone.bicep'
      - 'landing-zone/modules/parameters/landing-zone.parameters.json'
      - '.github/workflows/landing-zone-ci.yml'
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login using OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy landing-zone.bicep
        run: |
          az deployment sub create \
            --location eastus \
            --template-file infra/landing-zone.bicep \
            --parameters infra/landing-zone.parameters.json
