# ------------------------------------------------------------
# .github/workflows/landing-zone-ci.yml
# ------------------------------------------------------------
name: Deploy Landing Zone

on:
  push:
    branches:
      - main
    paths:
      - 'landing-zone/landing-zone.bicep'
      - 'landing-zone/modules/parameters/landing-zone.parameters.json'
      - '.github/workflows/landing-zone-ci.yml'

permissions:
  id-token: write
  contents: read

jobs:
  deploy-landing-zone:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login using OIDC
        uses: azure/login@v1
        with:
          client-id:       ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id:       ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy landing-zone.bicep at Subscription Scope
        run: |
          az deployment sub create \
            --location eastus \
            --template-file landing-zone/landing-zone.bicep \
            --parameters landing-zone/modules/parameters/landing-zone.parameters.json
