# ─────────────────────────────────────────────────────────────────────────────
# File: .github/workflows/landing-zone-ci.yml
# Description: Deploy the subscription-scoped landing-zone orchestrator using OIDC.
#   1) Trigger: On push to main that touches landing-zone.bicep or its parameters.
#   2) Azure Login via azure/login@v1 (OIDC, no client secret).
#   3) Run `az deployment sub create …` to execute landing-zone.bicep.
# ─────────────────────────────────────────────────────────────────────────────
name: Deploy Landing Zone

on:
  push:
    branches:
      - main
    paths:
      - 'landing-zone/landing-zone.bicep'
      - 'landing-zone/parameters/landing-zone.parameters.json'
      - '.github/workflows/landing-zone-ci.yml'

permissions:
  id-token: write   # for OIDC login
  contents:  read   # to checkout code

jobs:
  deploy-landing-zone:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Azure OIDC login
      - name: Azure Login using OIDC
        uses: azure/login@v1
        with:
          client-id:       ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id:       ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # 3) Subscription-scope deploy
      - name: Deploy landing-zone.bicep (Subscription Scope)
        run: |
          az deployment sub create \
            --location eastus \
            --template-file landing-zone/landing-zone.bicep \
            --parameters landing-zone/parameters/landing-zone.parameters.json
