name: Deploy Landing Zone Infrastructure

on:
  push:
    paths:
      - 'landing-zone/**'
      - '.github/workflows/landing-zone-ci.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Landing Zone Bicep Template
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
          template: ./landing-zone/landing-zone.bicep
          parameters: ./landing-zone/parameters/landing-zone.parameters.json
          deploymentName: landingZoneDeployment
