# File: .github/workflows/provision-all.yml
name: Provision All Subscriptions

# We only run this manually, so use workflow_dispatch.
on:
  workflow_dispatch:

env:
  # These GitHub Secrets must already exist under Settings → Secrets → Actions:
  AZURE_TENANT_ID:      ${{ secrets.AZURE_TENANT_ID }}         # Your Azure AD Tenant ID
  AZURE_OIDC_CLIENT_ID: ${{ secrets.AZURE_OIDC_CLIENT_ID }}    # App Registration (federated SP) Client ID
  MANAGEMENT_SUB_ID:    ${{ secrets.MANAGEMENT_SUB_ID }}       # A subscription where that SP has User Access Admin on "/"

jobs:
  provision-all-subs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login via OIDC
        uses: azure/login@v1
        with:
          # Use SERVICE_PRINCIPAL along with a GitHub OIDC token
          client-id:               ${{ env.AZURE_OIDC_CLIENT_ID }}
          tenant-id:               ${{ env.AZURE_TENANT_ID }}
          subscription-id:         ${{ env.MANAGEMENT_SUB_ID }}
          auth-type:               SERVICE_PRINCIPAL
          use-github-federated-token: true
          allow-no-subscriptions:  true

          # ——— OR Classic Client-Secret Mode ——
          # If you cannot use OIDC, comment out the above block and uncomment:
          # client-id:             ${{ secrets.CLASSIC_SP_CLIENT_ID }}
          # client-secret:         ${{ secrets.CLASSIC_SP_CLIENT_SECRET }}
          # tenant-id:             ${{ secrets.AZURE_TENANT_ID }}
          # subscription-id:       ${{ secrets.MANAGEMENT_SUB_ID }}
          # auth-type:             SERVICE_PRINCIPAL

      - name: Run provision-subscriptions.ps1
        shell: pwsh
        run: |
          cd ./scripts
          pwsh ./provision-subscriptions.ps1

      - name: Confirm completion
        run: echo "✅ All subscriptions have been created and assigned to their Management Groups."
