# File: .github/workflows/provision-all.yml

name: Provision All Subscriptions

# This workflow does NOT run on push; it only runs when you click "Run workflow" manually
on:
  workflow_dispatch:

env:
  # These secrets must already exist in GitHub → Settings → Secrets → Actions
  AZURE_TENANT_ID:      ${{ secrets.AZURE_TENANT_ID }}         # Your Azure AD Tenant ID
  AZURE_OIDC_CLIENT_ID: ${{ secrets.AZURE_OIDC_CLIENT_ID }}    # Client ID of your federated App Registration
  MANAGEMENT_SUB_ID:    ${{ secrets.MANAGEMENT_SUB_ID }}       # Subscription ID where SP has User Access Admin on "/"

jobs:
  provision-all-subs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login via OIDC (azure/login@v2)
        uses: azure/login@v2
        with:
          client-id:       ${{ env.AZURE_OIDC_CLIENT_ID }}
          tenant-id:       ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.MANAGEMENT_SUB_ID }}
          auth-type:       service_principal
          oidc:            true
          allow-no-subscriptions: true

          # ——— OR Classic Client-Secret Mode ———
          # If you cannot use OIDC, comment out the above block and uncomment:
          # client-id:         ${{ secrets.CLASSIC_SP_CLIENT_ID }}
          # client-secret:     ${{ secrets.CLASSIC_SP_CLIENT_SECRET }}
          # tenant-id:         ${{ secrets.AZURE_TENANT_ID }}
          # subscription-id:   ${{ secrets.MANAGEMENT_SUB_ID }}
          # auth-type:         service_principal
          # oidc:              false

      - name: Run provision-subscriptions.ps1
        shell: pwsh
        run: |
          cd ./scripts
          pwsh ./provision-subscriptions.ps1

      - name: Confirm completion
        run: echo "✅ All subscriptions have been created and assigned into their Management Groups."
