# File: .github/workflows/provision-all.yml
name: Provision All Subscriptions

on:
  workflow_dispatch:

# Allow OIDC login
permissions:
  id-token: write
  contents: read

env:
  AZURE_TENANT_ID:      ${{ secrets.AZURE_TENANT_ID }}
  AZURE_OIDC_CLIENT_ID: ${{ secrets.AZURE_OIDC_CLIENT_ID }}
  MANAGEMENT_SUB_ID:    ${{ secrets.MANAGEMENT_SUB_ID }}

jobs:
  provision-all-subs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login via OIDC (azure/login@v2)
        uses: azure/login@v2
        with:
          client-id:       ${{ env.AZURE_OIDC_CLIENT_ID }}
          tenant-id:       ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.MANAGEMENT_SUB_ID }}
          auth-type:       service_principal
          allow-no-subscriptions: true
          audience:        api://AzureADTokenExchange

      - name: Install “account” CLI extension (preview)
        run: |
          az extension add --name account --allow-preview

      - name: Install “billing” CLI extension (preview)
        run: |
          az extension add --name billing --allow-preview

      - name: Run provisioning script
        shell: pwsh
        run: |
          cd ./scripts
          pwsh ./provision-subscriptions.ps1

      - name: Confirm completion
        run: echo "✅ Finished creating and assigning subscriptions."
